language: generic
dist: xenial
services:
  - docker

env:
  global:
    - DOCKER_URL="docker.quid.com"
    # travis encrypt DOCKER_USERNAME=codersofthedark

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: build & test
      name: "Build Docker image"
      script:
        - docker build -t codersofthedark/echo-server:$TRAVIS_TAG .
        - docker push codersofthedark/echo-server:$TRAVIS_TAG
